
  create table "public"."invoices" (
    "id" uuid not null default gen_random_uuid(),
    "tenant_id" uuid,
    "amount" bigint,
    "due_data" text,
    "status" text,
    "type" text
      );



  create table "public"."maintainance_requests" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "property_id" bigint,
    "unit_id" bigint,
    "created_by" uuid,
    "assigned_staff_id" uuid,
    "title" text,
    "description" text,
    "status" text,
    "priority" text
      );



  create table "public"."messages" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "sender_id" uuid,
    "receiver_id" uuid,
    "is_read" text
      );



  create table "public"."profiles" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "full_name" text,
    "email" text,
    "role" text,
    "avatar_url" text
      );



  create table "public"."properties" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "address" text,
    "type" text,
    "image_url" text,
    "total_units" bigint
      );



  create table "public"."staff" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "phone_number" bigint,
    "specialization" text,
    "status" text
      );



  create table "public"."tenants" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "unit_id" uuid,
    "lease_start" text,
    "lease_end" text,
    "status" text
      );



  create table "public"."units" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "property_id" bigint
      );


CREATE UNIQUE INDEX maintainance_requests_pkey ON public.maintainance_requests USING btree (id);

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX properties_pkey ON public.properties USING btree (id);

CREATE UNIQUE INDEX staff_pkey ON public.staff USING btree (id);

CREATE UNIQUE INDEX tenants_pkey ON public.tenants USING btree (id);

CREATE UNIQUE INDEX units_pkey ON public.units USING btree (id);

alter table "public"."maintainance_requests" add constraint "maintainance_requests_pkey" PRIMARY KEY using index "maintainance_requests_pkey";

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."properties" add constraint "properties_pkey" PRIMARY KEY using index "properties_pkey";

alter table "public"."staff" add constraint "staff_pkey" PRIMARY KEY using index "staff_pkey";

alter table "public"."tenants" add constraint "tenants_pkey" PRIMARY KEY using index "tenants_pkey";

alter table "public"."units" add constraint "units_pkey" PRIMARY KEY using index "units_pkey";

alter table "public"."invoices" add constraint "invoices_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.profiles(id) not valid;

alter table "public"."invoices" validate constraint "invoices_tenant_id_fkey";

alter table "public"."maintainance_requests" add constraint "maintainance_requests_assigned_staff_id_fkey" FOREIGN KEY (assigned_staff_id) REFERENCES public.staff(id) not valid;

alter table "public"."maintainance_requests" validate constraint "maintainance_requests_assigned_staff_id_fkey";

alter table "public"."maintainance_requests" add constraint "maintainance_requests_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.profiles(id) not valid;

alter table "public"."maintainance_requests" validate constraint "maintainance_requests_created_by_fkey";

alter table "public"."maintainance_requests" add constraint "maintainance_requests_property_id_fkey" FOREIGN KEY (property_id) REFERENCES public.properties(id) not valid;

alter table "public"."maintainance_requests" validate constraint "maintainance_requests_property_id_fkey";

alter table "public"."maintainance_requests" add constraint "maintainance_requests_unit_id_fkey" FOREIGN KEY (unit_id) REFERENCES public.units(id) not valid;

alter table "public"."maintainance_requests" validate constraint "maintainance_requests_unit_id_fkey";

alter table "public"."messages" add constraint "messages_receiver_id_fkey" FOREIGN KEY (receiver_id) REFERENCES public.profiles(id) not valid;

alter table "public"."messages" validate constraint "messages_receiver_id_fkey";

alter table "public"."messages" add constraint "messages_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES public.profiles(id) not valid;

alter table "public"."messages" validate constraint "messages_sender_id_fkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."staff" add constraint "staff_id_fkey" FOREIGN KEY (id) REFERENCES public.profiles(id) not valid;

alter table "public"."staff" validate constraint "staff_id_fkey";

alter table "public"."tenants" add constraint "tenants_id_fkey" FOREIGN KEY (id) REFERENCES public.profiles(id) not valid;

alter table "public"."tenants" validate constraint "tenants_id_fkey";

alter table "public"."tenants" add constraint "tenants_unit_id_fkey" FOREIGN KEY (unit_id) REFERENCES public.profiles(id) not valid;

alter table "public"."tenants" validate constraint "tenants_unit_id_fkey";

alter table "public"."units" add constraint "units_property_id_fkey" FOREIGN KEY (property_id) REFERENCES public.properties(id) not valid;

alter table "public"."units" validate constraint "units_property_id_fkey";

grant delete on table "public"."invoices" to "anon";

grant insert on table "public"."invoices" to "anon";

grant references on table "public"."invoices" to "anon";

grant select on table "public"."invoices" to "anon";

grant trigger on table "public"."invoices" to "anon";

grant truncate on table "public"."invoices" to "anon";

grant update on table "public"."invoices" to "anon";

grant delete on table "public"."invoices" to "authenticated";

grant insert on table "public"."invoices" to "authenticated";

grant references on table "public"."invoices" to "authenticated";

grant select on table "public"."invoices" to "authenticated";

grant trigger on table "public"."invoices" to "authenticated";

grant truncate on table "public"."invoices" to "authenticated";

grant update on table "public"."invoices" to "authenticated";

grant delete on table "public"."invoices" to "postgres";

grant insert on table "public"."invoices" to "postgres";

grant references on table "public"."invoices" to "postgres";

grant select on table "public"."invoices" to "postgres";

grant trigger on table "public"."invoices" to "postgres";

grant truncate on table "public"."invoices" to "postgres";

grant update on table "public"."invoices" to "postgres";

grant delete on table "public"."invoices" to "service_role";

grant insert on table "public"."invoices" to "service_role";

grant references on table "public"."invoices" to "service_role";

grant select on table "public"."invoices" to "service_role";

grant trigger on table "public"."invoices" to "service_role";

grant truncate on table "public"."invoices" to "service_role";

grant update on table "public"."invoices" to "service_role";

grant delete on table "public"."maintainance_requests" to "anon";

grant insert on table "public"."maintainance_requests" to "anon";

grant references on table "public"."maintainance_requests" to "anon";

grant select on table "public"."maintainance_requests" to "anon";

grant trigger on table "public"."maintainance_requests" to "anon";

grant truncate on table "public"."maintainance_requests" to "anon";

grant update on table "public"."maintainance_requests" to "anon";

grant delete on table "public"."maintainance_requests" to "authenticated";

grant insert on table "public"."maintainance_requests" to "authenticated";

grant references on table "public"."maintainance_requests" to "authenticated";

grant select on table "public"."maintainance_requests" to "authenticated";

grant trigger on table "public"."maintainance_requests" to "authenticated";

grant truncate on table "public"."maintainance_requests" to "authenticated";

grant update on table "public"."maintainance_requests" to "authenticated";

grant delete on table "public"."maintainance_requests" to "postgres";

grant insert on table "public"."maintainance_requests" to "postgres";

grant references on table "public"."maintainance_requests" to "postgres";

grant select on table "public"."maintainance_requests" to "postgres";

grant trigger on table "public"."maintainance_requests" to "postgres";

grant truncate on table "public"."maintainance_requests" to "postgres";

grant update on table "public"."maintainance_requests" to "postgres";

grant delete on table "public"."maintainance_requests" to "service_role";

grant insert on table "public"."maintainance_requests" to "service_role";

grant references on table "public"."maintainance_requests" to "service_role";

grant select on table "public"."maintainance_requests" to "service_role";

grant trigger on table "public"."maintainance_requests" to "service_role";

grant truncate on table "public"."maintainance_requests" to "service_role";

grant update on table "public"."maintainance_requests" to "service_role";

grant delete on table "public"."messages" to "anon";

grant insert on table "public"."messages" to "anon";

grant references on table "public"."messages" to "anon";

grant select on table "public"."messages" to "anon";

grant trigger on table "public"."messages" to "anon";

grant truncate on table "public"."messages" to "anon";

grant update on table "public"."messages" to "anon";

grant delete on table "public"."messages" to "authenticated";

grant insert on table "public"."messages" to "authenticated";

grant references on table "public"."messages" to "authenticated";

grant select on table "public"."messages" to "authenticated";

grant trigger on table "public"."messages" to "authenticated";

grant truncate on table "public"."messages" to "authenticated";

grant update on table "public"."messages" to "authenticated";

grant delete on table "public"."messages" to "postgres";

grant insert on table "public"."messages" to "postgres";

grant references on table "public"."messages" to "postgres";

grant select on table "public"."messages" to "postgres";

grant trigger on table "public"."messages" to "postgres";

grant truncate on table "public"."messages" to "postgres";

grant update on table "public"."messages" to "postgres";

grant delete on table "public"."messages" to "service_role";

grant insert on table "public"."messages" to "service_role";

grant references on table "public"."messages" to "service_role";

grant select on table "public"."messages" to "service_role";

grant trigger on table "public"."messages" to "service_role";

grant truncate on table "public"."messages" to "service_role";

grant update on table "public"."messages" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "postgres";

grant insert on table "public"."profiles" to "postgres";

grant references on table "public"."profiles" to "postgres";

grant select on table "public"."profiles" to "postgres";

grant trigger on table "public"."profiles" to "postgres";

grant truncate on table "public"."profiles" to "postgres";

grant update on table "public"."profiles" to "postgres";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."properties" to "anon";

grant insert on table "public"."properties" to "anon";

grant references on table "public"."properties" to "anon";

grant select on table "public"."properties" to "anon";

grant trigger on table "public"."properties" to "anon";

grant truncate on table "public"."properties" to "anon";

grant update on table "public"."properties" to "anon";

grant delete on table "public"."properties" to "authenticated";

grant insert on table "public"."properties" to "authenticated";

grant references on table "public"."properties" to "authenticated";

grant select on table "public"."properties" to "authenticated";

grant trigger on table "public"."properties" to "authenticated";

grant truncate on table "public"."properties" to "authenticated";

grant update on table "public"."properties" to "authenticated";

grant delete on table "public"."properties" to "postgres";

grant insert on table "public"."properties" to "postgres";

grant references on table "public"."properties" to "postgres";

grant select on table "public"."properties" to "postgres";

grant trigger on table "public"."properties" to "postgres";

grant truncate on table "public"."properties" to "postgres";

grant update on table "public"."properties" to "postgres";

grant delete on table "public"."properties" to "service_role";

grant insert on table "public"."properties" to "service_role";

grant references on table "public"."properties" to "service_role";

grant select on table "public"."properties" to "service_role";

grant trigger on table "public"."properties" to "service_role";

grant truncate on table "public"."properties" to "service_role";

grant update on table "public"."properties" to "service_role";

grant delete on table "public"."staff" to "anon";

grant insert on table "public"."staff" to "anon";

grant references on table "public"."staff" to "anon";

grant select on table "public"."staff" to "anon";

grant trigger on table "public"."staff" to "anon";

grant truncate on table "public"."staff" to "anon";

grant update on table "public"."staff" to "anon";

grant delete on table "public"."staff" to "authenticated";

grant insert on table "public"."staff" to "authenticated";

grant references on table "public"."staff" to "authenticated";

grant select on table "public"."staff" to "authenticated";

grant trigger on table "public"."staff" to "authenticated";

grant truncate on table "public"."staff" to "authenticated";

grant update on table "public"."staff" to "authenticated";

grant delete on table "public"."staff" to "postgres";

grant insert on table "public"."staff" to "postgres";

grant references on table "public"."staff" to "postgres";

grant select on table "public"."staff" to "postgres";

grant trigger on table "public"."staff" to "postgres";

grant truncate on table "public"."staff" to "postgres";

grant update on table "public"."staff" to "postgres";

grant delete on table "public"."staff" to "service_role";

grant insert on table "public"."staff" to "service_role";

grant references on table "public"."staff" to "service_role";

grant select on table "public"."staff" to "service_role";

grant trigger on table "public"."staff" to "service_role";

grant truncate on table "public"."staff" to "service_role";

grant update on table "public"."staff" to "service_role";

grant delete on table "public"."tenants" to "anon";

grant insert on table "public"."tenants" to "anon";

grant references on table "public"."tenants" to "anon";

grant select on table "public"."tenants" to "anon";

grant trigger on table "public"."tenants" to "anon";

grant truncate on table "public"."tenants" to "anon";

grant update on table "public"."tenants" to "anon";

grant delete on table "public"."tenants" to "authenticated";

grant insert on table "public"."tenants" to "authenticated";

grant references on table "public"."tenants" to "authenticated";

grant select on table "public"."tenants" to "authenticated";

grant trigger on table "public"."tenants" to "authenticated";

grant truncate on table "public"."tenants" to "authenticated";

grant update on table "public"."tenants" to "authenticated";

grant delete on table "public"."tenants" to "postgres";

grant insert on table "public"."tenants" to "postgres";

grant references on table "public"."tenants" to "postgres";

grant select on table "public"."tenants" to "postgres";

grant trigger on table "public"."tenants" to "postgres";

grant truncate on table "public"."tenants" to "postgres";

grant update on table "public"."tenants" to "postgres";

grant delete on table "public"."tenants" to "service_role";

grant insert on table "public"."tenants" to "service_role";

grant references on table "public"."tenants" to "service_role";

grant select on table "public"."tenants" to "service_role";

grant trigger on table "public"."tenants" to "service_role";

grant truncate on table "public"."tenants" to "service_role";

grant update on table "public"."tenants" to "service_role";

grant delete on table "public"."units" to "anon";

grant insert on table "public"."units" to "anon";

grant references on table "public"."units" to "anon";

grant select on table "public"."units" to "anon";

grant trigger on table "public"."units" to "anon";

grant truncate on table "public"."units" to "anon";

grant update on table "public"."units" to "anon";

grant delete on table "public"."units" to "authenticated";

grant insert on table "public"."units" to "authenticated";

grant references on table "public"."units" to "authenticated";

grant select on table "public"."units" to "authenticated";

grant trigger on table "public"."units" to "authenticated";

grant truncate on table "public"."units" to "authenticated";

grant update on table "public"."units" to "authenticated";

grant delete on table "public"."units" to "postgres";

grant insert on table "public"."units" to "postgres";

grant references on table "public"."units" to "postgres";

grant select on table "public"."units" to "postgres";

grant trigger on table "public"."units" to "postgres";

grant truncate on table "public"."units" to "postgres";

grant update on table "public"."units" to "postgres";

grant delete on table "public"."units" to "service_role";

grant insert on table "public"."units" to "service_role";

grant references on table "public"."units" to "service_role";

grant select on table "public"."units" to "service_role";

grant trigger on table "public"."units" to "service_role";

grant truncate on table "public"."units" to "service_role";

grant update on table "public"."units" to "service_role";


